### ISSUE TITLE
Mask takes the wrong part of the image

### ISSUE THREAD

**Issue by MellowEdge** [hlky/stable-diffusion-webui#120] opened 2022-08-27 11:50 UTC
When using masks, the wrong part of the image as actually masked. This happens only when the image you imported is not 1:1 ratio. 
Wide image:
![image](https://user-images.githubusercontent.com/26963226/187028875-22dff30d-28d4-4d7d-8670-a7144f534b4c.png)
Square image:
![image](https://user-images.githubusercontent.com/26963226/187028899-1459d6a8-4e5d-4b47-98a3-5d5db028c7d6.png)

**Comment by MellowEdge** [comment] 2022-08-27 12:38
Are you sure this is not because of the changes in repo? It worked properly like 2 days ago

**Comment by hlky** [comment] 2022-08-27 13:16
> Are you sure this is not because of the changes in repo? It worked properly like 2 days ago

There's been an update with an advanced editor since, it is highly experimental and very tempremental

For non square images I would suggest applying the mask in photoshop or [photopea](https://www.photopea.com/) it's just a gaussian blur 

Maybe the person who implemented the advanced editor knows what the issue is, probably something in the code setting the width and height to the same somewhere in the new advanced editor stuff

**Comment by altryne** [comment] 2022-08-27 16:13
@hlky the advanced editor seems to be super flaky in experience as well, and not super useful? 🤔

**Comment by hlky** [comment] 2022-08-27 18:02
> @hlky the advanced editor seems to be super flaky in experience as well, and not super useful? 🤔

Not particularly, it's good if you know what you're doing and are prepared to deal with how temperamental it is, but it's really a red herring that distracts some users, I mean it's img2img the prompt images you're meant to be using are either very simple sketches which shouldn't need cropping or masking in the ui, or it's an image from txt2img that you want to regenerate, but then if you're serious about regenerating it you would probably apply the gaussian blur yourself.

>probably something in the code setting the width and height to the same somewhere in the new advanced editor stuff

It's probably something like this

**Comment by oldfndm** [comment] 2022-08-27 18:23
If it's causing issues it should probably be removed, especially if it's not being used.

**Comment by hlky** [comment] 2022-08-27 22:58
> If it's causing issues it should probably be removed, especially if it's not being used.

It's being used, just needs to be documented a bit better so people know the limitations and workarounds, closing this for now

**Closed by hlky** 2022-08-27 22:58 UTC
Labels: bug, notabug, workaround
