### ISSUE TITLE
New interface is a whole BUG 

### ISSUE THREAD

**Issue by paciox** [hlky/stable-diffusion-webui#475] opened 2022-09-01 22:11 UTC
### What happened?

First look at #445 
Why the buttons to use upscale and face fix are removed and those function are moved to a separate tab?
LOL!

![image](https://user-images.githubusercontent.com/6546735/188021517-00f48db8-7fd1-4206-997b-4dd51c3a50c1.png)

Then restore multibatch.

Also #403, since the interface is now clunky about upscaling, at least provide buttons to send images to it

Then the just resize 
#445 

Lol, calm down with all of these UI revolutions, you're making more damage than else.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devilismyfriend** [comment] 2022-09-01 23:02
My man there's nothing wrong with changing stuff, especially so early on, this is a development repo, if you want a more stable experience there's a stable repo

**Comment by paciox** [comment] 2022-09-01 23:25
> My man there's nothing wrong with changing stuff, especially so early on, this is a development repo, if you want a more stable experience there's a stable repo, I have a PR to bring back those options to img2img

![image](https://user-images.githubusercontent.com/6546735/188028983-e6c74962-f09b-46ac-bf71-10240d5c3d14.png)

**Comment by hopibel** [comment] 2022-09-02 01:50
> My man there's nothing wrong with changing stuff, especially so early on, this is a development repo, if you want a more stable experience there's a stable repo, I have a PR to bring back those options to img2img

The issue is these changes break quite a few things but were still merged into the stable repo

**Comment by altryne** [comment] 2022-09-03 00:31
Folks, let's be civil. 

>The issue is these changes break quite a few things but were still merged into the stable repo 

We're introducing releases and changes will be synced into the main repo only when we cut a release. 

>My man there's nothing wrong with changing stuff,

We need to be more careful with changes that affect our users, we have a lot of folks enjoying this, and arbitrary decisions like "let me remove some features" need to be reviewed by the core team

**Closed** 2022-09-03 00:31 UTC
Labels: bug
