### ISSUE TITLE
[BUG] Optimized mode is broken

### ISSUE THREAD

**Issue by DenkingOfficial** [hlky/stable-diffusion-webui#319] opened 2022-08-30 14:57 UTC
**Describe the bug**
Optimized mode is not working
I'm getting error while generation after downloading latest version from master branch

**To Reproduce**
1. Add "--optimized" flag in relauncher.py
2. Start webui
3. Specify prompt and click "Generate"
4. See error in logs
```
  0%|                                                                                           | 0/50 [00:00<?, ?it/s]
!!Runtime error (txt2img)!!
 Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
exiting...calling os._exit(0)
Relauncher: Process is ending. Relaunching in 0.5s...
```

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - GPU: RTX 2060 Super
 - RAM: 16 GB
 - CPU: Intel i5-9400F

**Comment by athu16** [comment] 2022-08-30 15:00
It's happening after commit fe17340
![image](https://user-images.githubusercontent.com/93036639/187471246-fbc2c186-32c4-4d4e-a820-640fcc474323.png)
I believe with optimized mode the model isn't getting transferred to the GPU at all now, hence the multiple devices error

**Comment by DenkingOfficial** [comment] 2022-08-30 15:24
Thanks so much, changed code by myself and now it works like a charm!
Anyways, waiting for fix by @hlky

**Comment by hlky** [comment] 2022-08-30 15:29
@DenkingOfficial this was added a couple of hours ago it was supposed to be a fix for oom someone said, will revert it, sorry, I can only go off what optimized users are saying, I dont have a 4gb card

**Comment by oobabooga** [comment] 2022-08-30 15:31
Works for me, I could not reproduce this bug...

**Comment by athu16** [comment] 2022-08-30 15:34
@oobabooga are you using the optimised switch?

**Comment by oobabooga** [comment] 2022-08-30 15:35
@athu16 yes

model.cuda() is also never called on the basujindal version:
https://github.com/basujindal/stable-diffusion/blob/main/optimizedSD/optimized_txt2img.py

**Comment by throwaway-mezzo-mix** [comment] 2022-08-30 15:40
> It's happening after commit [fe17340](https://github.com/hlky/stable-diffusion-webui/commit/fe173407fe08cf496ef1607bbce3100f21bf4b3e) ![image](https://user-images.githubusercontent.com/93036639/187471246-fbc2c186-32c4-4d4e-a820-640fcc474323.png) I believe with optimized mode the model isn't getting transferred to the GPU at all now, hence the multiple devices error

i tried reverting that change locally too but i'm sharing @oobabooga's experience in that it doesn't even launch then.

**Comment by AscendedGravity** [comment] 2022-08-30 15:46
Same error occurs per OP when using either the optimized tag or optimized-turbo.

GTX 1070 8gb

**Comment by throwaway-mezzo-mix** [comment] 2022-08-30 15:48
I've taken another look at that section and that commit seems to make very little sense after slightly closer inspection
![Screenshot 2022-08-30 174624](https://user-images.githubusercontent.com/110428425/187482195-78180b7d-4b78-4d7e-9894-9627fd2c76da.png)
That "if" could never succeed.

**Comment by hlky** [comment] 2022-08-30 15:49
Ok so it's working for @DenkingOfficial @athu16 with fe17340 reverted
How about @throwaway-mezzo-mix @AscendedGravity have you updated since I reverted that commit?

**Comment by hlky** [comment] 2022-08-30 15:51
@oobabooga it doesn't work for you without fe17340 aka .cuda never called as @throwaway-mezzo-mix pointed out

so, what card do you have?

could everyone state their graphics card?

**Comment by oobabooga** [comment] 2022-08-30 15:57
GTX 1650 4GB

Linux mint, running with `--precision full --no-half`

> Same error occurs per OP when using either the optimized tag or optimized-turbo.
> 
> GTX 1070 8gb

With 8GB you can fit the entire model into VRAM at once. Optimized version exists to allow 4GB GPUs to run SD.

**Comment by throwaway-mezzo-mix** [comment] 2022-08-30 15:57
Also @hlky i've updated my webui.py now and reverting it seemed to work.

**Comment by athu16** [comment] 2022-08-30 15:57
RTX 2060 Mobile 6GB

**Comment by AscendedGravity** [comment] 2022-08-30 15:58
> @AscendedGravity have you updated since I reverted that commit?

Did a manual revert of https://github.com/hlky/stable-diffusion-webui/commit/fe173407fe08cf496ef1607bbce3100f21bf4b3e an yes the optimized-turbo tag functions.

> With 8GB you can fit the entire model into VRAM at once. Optimized version exists to allow 4GB GPUs to run SD.

While true, I can run higher image sizes and/or larger batch sizes with optimized.

**Comment by oobabooga** [comment] 2022-08-30 16:01
If it works for everyone but me this issue can be closed and reopened later if someone else experiences the same issue. Maybe I'm doing something wrong.

**Comment by throwaway-mezzo-mix** [comment] 2022-08-30 16:11
> Linux mint, running with `--precision full --no-half`
@oobabooga Just to make sure, were you running with --optimized when testing this change? Because that's the only time it would affect you.
That might explain why your experience is different.

**Comment by throwaway-mezzo-mix** [comment] 2022-08-30 17:04
> Yes

I'm out of ideas, then. Maybe someone else still has an idea?

**Comment by oobabooga** [comment] 2022-08-30 17:07
Is it possible that some of you are running code from

https://github.com/hlky/stable-diffusion

and not

https://github.com/hlky/stable-diffusion-webui

?

**Closed** 2022-08-31 12:13 UTC

**Comment by GeorgeTownsendd** [comment] 2022-09-05 04:10
Just adding my experience here. 

This repo works fine on windows, no issues with any functionality when running optimised mode on a 1050ti 4GB. 

On arch, once again with optimised mode, I get OOM error on startup. With the "if not opt.optimised: model.cuda()" block in webui.py, the application starts, but I get the "found at least two devices, cuda:0 and cpu!" error from the OP when I try to run any prompt. 

Thought the OS factor may be relevant to someone more knowledgeable than myself.
