### ISSUE TITLE
[BUG]cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by alexfredo** [hlky/stable-diffusion-webui#146] opened 2022-08-27 18:35 UTC
Hi when I click on generate I have this bug : cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
Please help me  !! thanks

**Comment by hlky** [comment] 2022-08-27 18:38
@alexfredo there is a template for a reason, it helps people to fix your issue

What operating system?
What graphics card do you have?
Are you using --optimized?

**Comment by alexfredo** [comment] 2022-08-27 18:40
I have windows 10
geforce rtx 2060
I don't use --optimized

**Comment by alexfredo** [comment] 2022-08-27 18:45
How I can use --optimized ?

**Comment by hlky** [comment] 2022-08-27 20:16
Look at the readme

**Comment by hlky** [comment] 2022-08-27 20:17
Closing because unreproducible for now, seems to be hardware issue, and not enough information provided

**Closed by hlky** 2022-08-27 20:16 UTC
