### ISSUE TITLE
[BUG] Drawing circle lags behind the mouse when painting a mask on the Image-to-Image mask editor.

### ISSUE THREAD

**Issue by ZeroCool940711** [hlky/stable-diffusion-webui#198] opened 2022-08-28 16:49 UTC
**Describe the bug**
When painting a mask on the Image to Image mask editor the round drawing wheel lags behind the mouse and only moves when the mouse reaches the outside of the circle, here on this screenshot you can see what I mean.
![image](https://user-images.githubusercontent.com/5977640/187084878-5d1d7d30-fae3-445b-9c98-d28cfe311361.png)
The smaller gray circle that the red arrow with the number 1 is pointing at is where the mouse is and the big gray circle is where it will be actually painting, because of this small input lag drawing precise masks can be a bit hard, I think the drawing circle should move with the mouse at it center, where the point of the second red arrow with the number 2 is, this will make drawing the mask a lot easier, faster and we will be able to draw it with more precision.  

**To Reproduce**
1. Go to the Image to Image tab
2. Select the "Mask" option under "Image Editor Mode"
3. Load a new image or use the default image on the editor.
4. Move your mouse over the image to start drawing and watch the gray circle lag behind the mouse as you struggle to paint with it.

**Expected behavior**
The expected behavior would be the gray circle moving with the mouse at it center, and moving at the same speed as the mouse, this would make drawing a mask a lot easier.

**Screenshots**
![image](https://user-images.githubusercontent.com/5977640/187084878-5d1d7d30-fae3-445b-9c98-d28cfe311361.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 -  OS Build: 19044.1889
 - Browser: Brave Browser
 - Version: latest version at the time of writing this issue.

**Comment by Alphyn-gunner** [comment] 2022-08-28 17:07
Are you sure about it not being the expected behavior? I thought It was brush smoothing aka lazy mouse.

**Comment by ZeroCool940711** [comment] 2022-08-28 17:10
@Alphyn-gunner so it's meant to be like that?, I thought it was a bug, in that case I think I should change the issue to be a feature requests and ask for an option to disable that behavior and make it so it follows the mouse as I mentioned before.

**Comment by Alphyn-gunner** [comment] 2022-08-28 17:15
After some testing: Yeah, I'm pretty sure it's working as intended. But you're right, it would be nice to be able to toggle this behavior.

There are definitely some issues with the masked mode, though. Masking doesn't work work for me half the time at all. Sometimes i only see the small gray circle but not the big white one and cannot. 
And if your browser page zoom is set to anything but 100% it will be messed up 10 out of 10 times. The gray circle will not follow the mouse cursor.

**Comment by ZeroCool940711** [comment] 2022-08-28 17:19
> Sometimes i only see the small gray circle but not the big white one and cannot draw
Oh, I had that behavior, that usually happens when the image has a different size than the canvas or your output image size, not sure which one but it's one of those, I think that what's happening is that the real brush is outside the canvas and you only see the small gray circle which is for the mouse position, when you see that behavior just switch to crop and then back to mask mode and it should be fixed, if not the first time do it a couple of times.

**Comment by hlky** [comment] 2022-08-29 20:49
Gradio will be making some changes soon that should solve all the issues with the image editor, so i'm going to close this for now.

**Closed by hlky** 2022-08-29 20:49 UTC
Labels: img2img, UI
