### ISSUE TITLE
[FEATURE REQUEST] we can get you a100s for training Textual Inversion

### ISSUE THREAD

**Issue by christophschuhmann** [hlky/stable-diffusion-webui#331] opened 2022-08-30 18:31 UTC
Hi, I am one of the chairman of LAION https://laion.ai . We are closely connected to stability.ai and have access to their GPU Cluster.
If you are interested in training Textual Inversion and need GPUs, please connect to me on discord
spirit-from-germany#1488

Kind regards, Christoph Schuhmann

**Comment by JohannesGaessler** [comment] 2022-08-30 19:47
Is the cluster intended for textual inversion exclusively?
I wrote a Python script to quantitatively investigate whether square brackets, round brackets, or exclamation marks actually strengthen or weaken the effect of keywords using likelihood methods.
The methodology is to apply e.g. brackets to keywords such as "red", "blue", or "green" and to numerically evaluate how the corresponding pixel values change across the generated images.
A linear model with the number of brackets on the x axis and the change in pixel value on the y axis is fitted to the data.
The current state of the analysis can be found here:
https://github.com/JohannesGaessler/stable-diffusion-tools/tree/master/emphasis
Results are currently inconclusive.
(The value for chi2/NDF is much smaller than one so my methodology may be incorrect, but this may also just be due to the limited amount of data.)

Currently, since I only have a GTX 1070 I am bottlenecked on the compute necessary to generate the data.
I would gladly accept access to a compute cluster when given the chance.
Alternatively I would offer assistance if someone else wanted to do this analysis in my stead.
In case it's relevant: I am an experimental particle physicist and current lead developer of the software project "kafe2", a framework for nonlinear regression that is used internally at the physics department of the Karlsruhe Institute of Technology.

**Comment by hlky** [comment] 2022-08-30 20:02
@christophschuhmann hlky#8470

**Comment by christophschuhmann** [comment] 2022-08-30 20:20
The clusters of course not only for textual inversion. But I think that we can get each of you a few A100s for your projects. - Please, let’s move to discord. The LAION and the Stability team mostly communicate over discord. :)

spirit-from-germany#1488

**Comment by hlky** [comment] 2022-08-30 20:21
@christophschuhmann we just couldn't add you

**Comment by christophschuhmann** [comment] 2022-08-30 20:23
yea? - Altryne just PMed me :)

**Comment by JohannesGaessler** [comment] 2022-08-30 20:25
My current Name on Discord is "DER RÜTTLER".

**Comment by JohannesGaessler** [comment] 2022-08-30 20:29
Sorry for the stupid question, I rarely use Discord:
Which buttons am I supposed to press?
I can't seem to add @christophschuhmann as a friend, so am I supposed to post my handle instead?
DER RÜTTLER#1032

**Comment by rinongal** [comment] 2022-08-30 20:45
@hlky @altryne I'm also available on discord if you need a hand with anything textual-inversion related. Sylvver#2478

**Comment by nom57** [comment] 2022-08-30 20:55
@christophschuhmann I am unable to add you on discord as it says I cannot message you / you are not accepting friend requests.

I have a very big model project with a carefully curated and aided dataset that I would need help with.
my discord id : Goup#4799

**Comment by nom57** [comment] 2022-08-30 20:59
@rinongal I also tried to add you

**Comment by altryne** [comment] 2022-08-30 22:14
> @hlky @altryne I'm also available on discord if you need a hand with anything textual-inversion related. Sylvver#2478

Sent. I'm closing this issue for now folks

**Closed by altryne** 2022-08-30 22:14 UTC
Labels: enhancement
