### ISSUE TITLE
[BUG] The face correction doesn't work

### ISSUE THREAD

**Issue by search620** [hlky/stable-diffusion-webui#287] opened 2022-08-29 21:54 UTC
The face correction doesn't work
The results as without this face correction. :(
![image](https://user-images.githubusercontent.com/56544202/187305730-556f6395-dee5-4a2b-8caa-c3d1577f07cc.png)

**Comment by Alphyn-gunner** [comment] 2022-08-29 22:25
I did some testing. It works, it saves two images to the output folder, before and after the GFPGAN face correction. 
![image](https://user-images.githubusercontent.com/34932866/187307762-5702f82c-ce29-4161-bfdc-cadc79c4bea7.png)
Left - WebUI. Right - the second of the two images saved on disk.

The real issue, and it's kind of a bigger UI/UX issue is that WebUI only shows the original images before GFPGAN applied. 
It works exactly the same way with the RealESRGAN upscaler.
If you open a generated image in a new tab, or copy it to the clipboard, it uses the original 512x512 image, not the upscaled image.
If both GFPGAN and ESRGAN are enabled, it also saves two images, the originally generated and one with both effects applied in order, GFPGAN first. 
The UI only shows the original image. I think it is not what a user expects, as evidenced by this issue. So it would be nice if webui showed the final result.

**Comment by hlky** [comment] 2022-08-29 22:32
Given that's what people using those options want I've changed the output to function like that, if you don't want the original file to save just untick 'save individual samples' when using gfpgan/esrgan

**Comment by hlky** [comment] 2022-08-29 22:33
Please test that it functions as expected

**Comment by Alphyn-gunner** [comment] 2022-08-29 22:44
I've tested it, it works, but the original image is not saved in the folder anymore. 
It saves the GFPGAN image twice. If the upscaler is enabled, both saved images are upscaled.
![image](https://user-images.githubusercontent.com/34932866/187311773-eeb8688b-76a6-4130-a187-0ef21075fcf0.png)

**Comment by hlky** [comment] 2022-08-29 22:54
Now it should display the post-processed output, saved the original, and save the post-processed output, turning off 'save individual samples' now has no effect because that's not what you want anyway. 
Is this what you want?

**Comment by hlky** [comment] 2022-08-29 22:56
wait hang on

**Comment by search620** [comment] 2022-08-29 22:58
> both saved images are upscale
How do I fix it?
![2022-08-30_01-56-55](https://user-images.githubusercontent.com/56544202/187313197-f0324de7-ddaa-4db3-bd9e-c16e35537fe6.png)

**Comment by hlky** [comment] 2022-08-29 23:00
@search620 read the rest of this issue i am working on this right now

**Comment by hlky** [comment] 2022-08-29 23:02
@Alphyn-gunner try now, i forgot to add a check on save_image because saving images when post-processing is used is handled already by that point now, and I had used `original_image` but some of the rest of the code is expecting `image`  so best to stick to `image`

**Comment by devilismyfriend** [comment] 2022-08-29 23:13
> > both saved images are upscale
> > How do I fix it?
> > ![2022-08-30_01-56-55](https://user-images.githubusercontent.com/56544202/187313197-f0324de7-ddaa-4db3-bd9e-c16e35537fe6.png)

You seem to be using an older version since gobig is still in the options

**Comment by Alphyn-gunner** [comment] 2022-08-29 23:15
It looks like it's reverted to the original behavior. Both images are saved, but the original image is the one displayed in the UI.
It's getting pretty late, so I won't be able to test new commits right now if you do any, I hope other people here can help you with that. Thank you!

**Comment by hlky** [comment] 2022-08-29 23:18
Should be ok now, sorry. It's late here too, and I'm just pushing what I think should fix it 🚀

**Comment by hlky** [comment] 2022-08-30 08:43
Check #305 

Hopefully everything still functions as expected, #305 should have fixed the gfpgan/esrgan image not being used in the prompt combination grid, prompt matrix grid still needs to use the images from those options if selected. Although these are all edge cases imo, I think most people should just use gfpgan and esrgan as post-processing not all generated images are worth using it on, I know some people feel differently though.

**Comment by Alphyn-gunner** [comment] 2022-08-30 08:51
I've just tested the version from when I went to bed yesterday.
It saves both images, adds both of them to the grid and shows both in the webui.
I think this is the best case scenario, actually. 
![image](https://user-images.githubusercontent.com/34932866/187392921-40790acc-8f1d-4f08-a079-f3d21f170b4f.png)

The only problem I see is that with upscaled images the grid will get pretty enormous fast if many samples are generated. 
With only 2 samples it's 4096x4096 and 1 mb already.

I'm going to test the current version now.

**Comment by Alphyn-gunner** [comment] 2022-08-30 08:59
I actually forgot to enable the filters and just ran a t2i prompt with 3 samples.
I got this error:
![image](https://user-images.githubusercontent.com/34932866/187395514-f6a569c5-a46f-488f-b281-5049a44c8975.png)

**Comment by hlky** [comment] 2022-08-30 09:20
> I actually forgot to enable the filters and just ran a t2i prompt with 3 samples. I got this error: ![image](https://user-images.githubusercontent.com/34932866/187395514-f6a569c5-a46f-488f-b281-5049a44c8975.png)

This was caused by a pr by @JustOxlamon I assumed they tested it sorry, reverted.

**Comment by hlky** [comment] 2022-08-30 09:21
I'll look at your grid complaint now.

**Comment by hlky** [comment] 2022-08-30 09:25
Ok logic was the wrong way

`if not skip_save or (not use_GFPGAN or not use_RealESRGAN):`

now it should work @Alphyn-gunner

**Comment by Alphyn-gunner** [comment] 2022-08-30 09:36
Ok, everything seems to be working. The folder contains both the original and final image, the webui and the grid show only the final images.
Thanks for all the work! I think it's a very nice improvement.

**Comment by hlky** [comment] 2022-08-30 09:38
If this is all working for you I'll close this issue, thanks.

**Closed by hlky** 2022-08-30 09:38 UTC
Labels: awaitingtest

**Comment by search620** [comment] 2022-08-30 10:27
This bug still exists (I updated the version two hours ago)

The operation should be simple.
1. Save as a normal file (without extensions).
2. Save as separate files  (for each extension that check as enabled will save separately). 
3. Save as merged files (one file merged with all extensions enabled as one image). 

What do you think is possible to do it this way?

https://user-images.githubusercontent.com/56544202/187410855-7025355c-4268-4d0f-a71d-8623b7ed882a.mp4

**Comment by hlky** [comment] 2022-08-30 10:30
>2 hours ago

@search620 read the rest of the issue, this is fixed

**Comment by Alphyn-gunner** [comment] 2022-08-30 10:31
@search620 This was fixed an hour ago. Always update to the latest version before you test anything. I think it makes sense. Use the github app for convenience.
