### ISSUE TITLE
Caught in error loop

### ISSUE THREAD

**Issue by parsec501** [hlky/stable-diffusion-webui#33] opened 2022-08-25 20:40 UTC
When running webui.cmd, the dependencies are installed, but the it is stuck in this loop:
```
Relauncher: Launching...
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\sd-w\scripts\webui.py", line 2, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...
        Relaunch count: 1
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\sd-w\scripts\webui.py", line 2, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...
        Relaunch count: 2
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\sd-w\scripts\webui.py", line 2, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...
        Relaunch count: 3
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\sd-w\scripts\webui.py", line 2, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...
        Relaunch count: 4
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\sd-w\scripts\webui.py", line 2, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...
        Relaunch count: 5
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\sd-w\scripts\webui.py", line 2, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Relauncher: Process is ending. Relaunching in 0.5s...
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\sd-w\scripts\relauncher.py", line 11, in <module>
    time.sleep(0.5)
```

This is printed every two seconds. Is this intentional or a bug?

**Comment by hlky** [comment] 2022-08-25 20:45
`ModuleNotFoundError: No module named 'gradio'`
looks like the environment didn't install properly, it should have if you followed the instructions 

open your environment.yaml and tell me what the name is

did you follow the rentry guide?

**Comment by parsec501** [comment] 2022-08-25 21:47
Yes, I followed the guide and renamed it to lpo

Can I install the environment manually and then run the webui.cmd?

**Comment by hlky** [comment] 2022-08-25 21:50
yes try that if you want or just remove environment with `conda env remove -n ldo`, delete the folder, clone it again and try again from scratch

**Comment by parsec501** [comment] 2022-08-25 22:06
I did it again from scratch and same issue. Antivirus is off, firewall is off. I manually installed the environment, it installed correctly. It also is recognized correctly by webui.cmd ("already exists"). Still the gradio dependency issue

I manually activated the conda env and ran the webui script and it works without issues. GFPGAN works too

**Comment by hlky** [comment] 2022-08-25 22:23
weird, it works for most people

you did install conda as all users?

was the src folder empty before you ran webui? if it was a fresh clone it won't have existed but if you're 'upgrading' it will have been there and can cause issue with pip even when the environment name is different

**Comment by parsec501** [comment] 2022-08-25 22:34
> you did install conda as all users?


I'm actually not sure about that, I already had it installed beforehand. Does that make a difference?

**Comment by hlky** [comment] 2022-08-25 23:11
> Does that make a difference?

apparently so

what about the src folders? was it a fresh clone? existing? that is the other main cause of issues regarding environment atm

**Comment by parsec501** [comment] 2022-08-25 23:20
> > Does that make a difference?
> 
> apparently so
> 
> what about the src folders? was it a fresh clone? existing? that is the other main cause of issues regarding environment atm

Yes, it was a fresh clone

**Comment by hlky** [comment] 2022-08-25 23:36
os? specific version if win10 

just to try and narrow down what the issue is and why it only happens for some people

**Comment by Tavrin** [comment] 2022-08-26 00:00
Hey so I had the same problem and actually found that the path in webui.cmd was wrong for me, it points to `C:\ProgramData\miniconda3\Scripts\activate.bat` but miniconda is installed in my user directory.

Changing that to `%USERPROFILE%\miniconda3\Scripts\activate.bat` solved the issue for me

**Comment by ShinkoNet** [comment] 2022-08-26 00:09
We should add a folder exists check to webui.cmd so it changes the path of miniconda depending if it's installed for all users or not.
It's done for the model ckpt already so might as well try it for that

**Comment by hlky** [comment] 2022-08-26 00:13
>We should add a folder exists check to webui.cmd so it changes the path of miniconda depending if it's installed for all users or not.

good idea

> Also the guide should just ensure everything is in ldm and that we're not editing environment.yaml anymore to change the environment name.

I think this too, if the links to the old guides were just removed people would stop using them, and they can remove their old environment called ldm if they have one, renaming the environment adds needless complexity to something that's supposed to be easy to setup

The person making the rentry guide thinks otherwise though

**Comment by heartlocket** [comment] 2022-08-26 00:20
i personally know of many users having this issue!!! the guide should really have troubleshooting or a suggestion for this. I followed the first steps exactly and its failing at gradio module

**Comment by hlky** [comment] 2022-08-26 00:25
> the guide should really have troubleshooting or a suggestion for this.

it does

it's probably because you didn't install conda for all users

> Hey so I had the same problem and actually found that the path in webui.cmd was wrong for me, it points to `C:\ProgramData\miniconda3\Scripts\activate.bat` but miniconda is installed in my user directory.
> 
> Changing that to `%USERPROFILE%\miniconda3\Scripts\activate.bat` and `call %USERPROFILE%\miniconda3\Scripts\activate.bat ldo` solved the issue for me

**Comment by heartlocket** [comment] 2022-08-26 00:41
> 

this is most definitely not a fix. it doesnt matter what the path is, it is still stuck on gradio, even when pointing properly to activate.bat

**Comment by hlky** [comment] 2022-08-26 00:44
>activate.bat

You're using an old guide and an old version of the repo

activate.bat was removed around 12 hours ago

**Comment by heartlocket** [comment] 2022-08-26 00:45
> > activate.bat
> 
> You're using an old guide and an old version of the repo
> 
> activate.bat was removed around 12 hours ago

uhhh you just told me to fix my path to activate.bat..... ?????

**Comment by hlky** [comment] 2022-08-26 00:51
read it wrong, there was an old auto installer with a similar name

either way this is not my problem, it's an issue on your end, there's nothing wrong with the instructions, it works, people have literally just tested it from scratch and it works

closing the issue, i will make a new issue where you can post detailed information about your setup to determine the common factor for people experiencing issues

if you comment on the issue without including the request information about your setup you will be ignored

**Closed by hlky** 2022-08-26 00:51 UTC
Labels: notabug
