### ISSUE TITLE
[Bug]: Gobig or GoLatent upscale gave me this error

### ISSUE THREAD

**Issue by Jpkovas** [hlky/stable-diffusion-webui#520] opened 2022-09-02 15:30 UTC
### What happened?

When the gobig or golatent option is selected, this error appears in the cmd after 1 iteration
![CWINDOWSsystem32cmd exe_Zbko3V41U4-020922](https://user-images.githubusercontent.com/11709313/188183487-59f25590-1867-4494-a66e-ebcc20edb6dd.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
--optimized-turbo
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Cainor** [comment] 2022-09-02 15:39
This is duplicate of: https://github.com/hlky/stable-diffusion-webui/issues/464

**Closed** 2022-09-03 00:24 UTC
Labels: bug
