### ISSUE TITLE
[BUG] Denoising Strength seems to have no effect in Img2Img

### ISSUE THREAD

**Issue by Volan360** [hlky/stable-diffusion-webui#150] opened 2022-08-27 19:01 UTC
**Describe the bug**
Regardless of denoising strength, any img2img generations seem to completely overpower the image

**To Reproduce**
1. Choose a starting image and set the prompt
2. Change denoising strength to any value
3. Take note of generated image
4. Repeat with a very different denoising strength
5. The amount of change from the starting image is the same

**Expected behavior**
Changing the denoising strength changes how much of an effect img2img has on the starting image
**Screenshots**
Extremely low denoising strength:
![image](https://user-images.githubusercontent.com/20827578/187044416-81c6bf98-48c4-42b2-b191-3ce4adb627a0.png)

Extremely high denoising strength:
![image](https://user-images.githubusercontent.com/20827578/187044444-5377ce6c-aff7-4443-82eb-263bcec0c6b9.png)

CMD output for both cases (same number of steps for some reason):
![image](https://user-images.githubusercontent.com/20827578/187044453-d9f8e42a-9760-484c-83ed-67e8bfb5b10f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave Browser
 - Version: Master

**Additional context**

**Comment by hlky** [comment] 2022-08-27 20:27
I notice the seed has not been kept the same, leaving the seed box blank generates a random seed each time which will produce vastly different results.

Can you try again but set a seed in the input box so it's the same each generation? I believe this will better demonstrate to you the effect of denoising strength.

Plus the amount of change is hard to quantify, if you only want to change part of the image use the masking feature, but note it can be temperamental, masking in the UI is for quick tests/changes really, if you want better results apply the mask yourself, it's just a gaussian blur, you can use something like photoshop or photopea

Will leave this open because your idea for a 'range' of denoising strength could be added where the increase is spread evenly across the batch size, so if the range was 0.3 to 0.8 with  batch size 6 it would start at 30 and increase by 0.1 each time, when used with the same seed could be useful to the see the effect.

**Comment by Volan360** [comment] 2022-08-27 21:00
Here's another go with the seed being kept constant
Very low denoising:
![image](https://user-images.githubusercontent.com/20827578/187047763-248ea7d9-fcaf-4d98-aa54-f1aff2ed6c39.png)

Very High denoising:
![image](https://user-images.githubusercontent.com/20827578/187047785-070db1a0-bad1-4506-883e-c99ee66c340d.png)

While the images are different, it seems to me that they are both drastically changing the original image. With an earlier build I had (I think from yesterday or the day before), very low denoising strength would result in almost no change whatsoever.

**Comment by ivdos** [comment] 2022-08-27 21:49
@hlky the error in the sampler still remains. Now it just works the same way as in txt2img, because it doesn't get noise. I wrote here how I fixed it #125

**Comment by Alphyn-gunner** [comment] 2022-08-27 21:54
Yeah, we tested this a lot over at Discord support-and-questions channel, it seems to keep some resemblance to the image only if you set denoising to the lowest possible value, 0.01.

**Comment by RubenWB** [comment] 2022-08-27 21:59
this issue is best demonstrated for me when masking the image- setting it at 0.02 yields images that vastly do not match output (should be a carbon copy right?)

**Comment by RubenWB** [comment] 2022-08-27 22:01
single egg, solid white background
Steps: 50, Sampler: k_lms, CFG scale: 7.5, Seed: 807746643
![image](https://user-images.githubusercontent.com/98309433/187049385-cf251130-c049-4940-8f96-f856b7997b94.png)
![image](https://user-images.githubusercontent.com/98309433/187049445-eeac9ee0-3273-48f9-bcfd-f5c9538b6303.png)

Set the seed value to 0

**Comment by Alphyn-gunner** [comment] 2022-08-27 22:14
![image](https://user-images.githubusercontent.com/34932866/187049523-c47e93ca-ec2c-4deb-b5f3-189c75b86bd0.png)
seed: 217822070
prompt: a fantasy landscape, trending on artstation
denoise: 0.1
cfg: 5
Compared to same settings, webui.py version from 26.08.22:
![image](https://user-images.githubusercontent.com/34932866/187049763-58be699c-6694-4d5a-864d-2bd08da01109.png)

**Comment by hlky** [comment] 2022-08-27 22:51
@Volan360 You are using mask mode, without setting a mask, yet set to keep masked area, therefore the entire image is being regenerated


@RubenWB 
> this issue is best demonstrated for me when masking the image- setting it at 0.02 yields images that vastly do not match output (should be a carbon copy right?)

Same issue here you are using keep masked area, and the area you have masked has been kept, the area not masked has been regenerated

@Alphyn-gunner I can't decipher which image is supposed to be which, format your comment better please, and the first two images I can't see whether you have keep masked area or regenerate masked area, the second two images I have no idea what you're trying to show here.

I think the issue all 3 of you are having is that you don't understand what img2img is supposed to do, and you don't understand what the options do so they aren't doing what you expect.

**Comment by Volan360** [comment] 2022-08-27 22:57
@hlky I understand that the whole image is being regenerated. The issue is that the strength of the change is not being affected by the denoise slider the way that it was 2 days ago. It used to be that the whole image would change, but only moderately at low levels. Now it is not taking the previous image into consideration at all, as if it was text2img.

**Comment by Alphyn-gunner** [comment] 2022-08-27 23:08
@hlky that is not the mask mode. All the examples are made in the crop mode. Denoising strength is ignored in the crop mode as well. The first two images show the difference between the new and the old behavior. 

The last two images illustrate that you cannot achieve a result so drastically different from the original image (the default drawing) using the old WebUI even at maximum denoise of 0.99 compared to the new WebUI at minimum denoise value of 0.01. The image generated by the new WebUI using the same seed doesn't even look remotely similar to the old ones. Where does it come from?

**Comment by codedealer** [comment] 2022-08-27 23:13
I'll try to hopefully pitch in with something useful.
Checked out the yesterday's repo:
Settings are 
```
man in white robe prophet character art by Charlie Bowater 4k artstation
Steps: 50, Sampler: k_lms, CFG scale: 10.5, Seed: 2052739210
```
**Crop mode**, Denoising Strength is at **0.1** so the output is basically the same as the input
![image](https://user-images.githubusercontent.com/4258136/187050939-e96b6717-f09a-48b8-8df8-a027b24b05c1.png)
Now the most recent one from https://github.com/hlky/stable-diffusion:
Same settings
```
man in white robe prophet character art by Charlie Bowater 4k artstation
Steps: 50, Sampler: k_lms, CFG scale: 10.5, Seed: 2052739210
```
**Crop mode**, Denoising Strength is at **0.1**
![image](https://user-images.githubusercontent.com/4258136/187051065-8d25c1e1-8d62-4201-822b-cd94809aa3d8.png)
The output is vastly different on a newly pulled version

**Comment by ivdos** [comment] 2022-08-27 23:30
It feels like no one reads my posts especially @hlky , I have already written 2 or 3 times what the problem is. Here at the very end #125 Already after it was closed. 
I apologize if I am difficult to understand because I am using a translator. By the way, the DIMM sampler works, because it was not touched.

**Comment by RubenWB** [comment] 2022-08-27 23:33
Apologies, I think your technical terminoligy went over our heads

Also. just in general Thank you for all of your hard work 🤩
We really really appreciate it!!

**Comment by remixz** [comment] 2022-08-27 23:34
It seems the regression was introduced here: https://github.com/hlky/stable-diffusion-webui/commit/10f8f4c0782daae847c62f8c3d88ae8f07f3cad2 If I revert this commit, I get the results everyone here is expecting, where a low denoising strength returns an image that's very similar to the input. (at the cost of bringing back the regression around it not using the selected sampler)

My Python is not great, but from my best understanding: In the `KDiffusionSampler` class' `sample` method, it never uses the sample count `S` when getting the amount of samples, while the previous code would attempt to. It also appears to never calculate anything with the noise value, while the previous code also did.

@ivdos's fix above does work to fix this, since it uses all of the calculated sample + noise parameters in the `img2img#sample` method. The alternative fix (which I believe was the intent of the above commit) would be to update the `KDiffusionSampler#sample` method to take in these additional parameters, to calculate the correct parameters. Essentially, this is a regression on moving to the shared `sample` method not taking into account more complex options.

**Comment by codedealer** [comment] 2022-08-27 23:35
> It feels like no one reads my posts especially @hlky , I have already written 2 or 3 times what the problem is. Here at the very end #125 Already after it was closed. I apologize if I am difficult to understand because I am using a translator. By the way, the DIMM sampler works, because it was not touched.

I read your issue but it seems like k_lms is also supposed to work and that is what I was using in my test? If your proposal fixes it I'm all for it, my friend!

**Comment by hlky** [comment] 2022-08-27 23:42
@ivdos why didn't you make a pr?

pushed, test it

**Closed by hlky** 2022-08-27 23:42 UTC

**Comment by ivdos** [comment] 2022-08-27 23:43
@hlky I don't know how to use github, I don't even know what pr is.

**Comment by Alphyn-gunner** [comment] 2022-08-28 00:06
@hlky 
This broke the entire thing for me.
`making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "scripts/webui.py", line 1986, in <module>
    [txt2img_prompt, txt2img_steps, txt2img_sampling, txt2img_toggles,goBig_strength,goBig_steps, txt2img_realesrgan_model_name, txt2img_ddim_eta, txt2img_batch_count, txt2img_batch_size, txt2img_cfg, txt2img_seed, txt2img_height, txt2img_width, txt2img_embeddings],
NameError: name 'goBig_strength' is not defined
Relauncher: Process is ending. Relaunching in 0.5s...`

**Comment by hlky** [comment] 2022-08-28 00:23
@Alphyn-gunner that's broken by something else, ill revert it
